kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: con1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello Ubunut; sleep 5 ; done"]

    - name: con2
      image: httpd
      ports:
        - containerPort: 80
  
