kind: Pod
apiVersion: v1
metadata:
  name: delhipod
  labels:                                                   
    department: dev
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-SevenMentor; sleep 5 ; done"]
